name: .NET
env:
  WORKING_REPO: 'WebApplication1/**'  
  OUTPUT_PATH: /tmp/output
on:
  workflow_dispatch:   
  push:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workspaceapichanged }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - '.github/workflows/**'
    # run only if changes detected in api 
      if: steps.filter.outputs.workspaceapichanged == 'true'
    - name: api change          
      uses: actions/checkout@v2
      with:
        amma-environment: ${{ inputs.amma-environment }}
        file-name: ${{ inputs.file-name }}
        artifact-name: ${{ inputs.file-path }}
        client-id: ${{ inputs.client-id }}
        workspace-name: ${{ inputs.workspace-name }}          
        client-secret: ${{ secrets.ARM_CLIENT_SECRET_AMMA_INTEGRATION }}