name: .NET

env:
  WORKING_REPO: 'BackEndServices/FleetIoT.Services/FleetIoT.Services'
  
on:
  workflow_dispatch:   
  push:
    branches: [ "main" ]
    paths:
      - WebApplication1/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: WebApplication1
    - name: Build
      run: dotnet build --no-restore
      working-directory: WebApplication1
    - name: dotnet publish
      run: dotnet publish -c Release -o myapp
      working-directory: WebApplication1
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      run: cmd ls
      with:
        files: appsettings.json'
      env:
       test: "ttttt"
       App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}